### ISSUE TITLE
Force close at launch

### ISSUE THREAD

**Issue by ewilly** [bencebeky/MMSKeeper#1]
Great idea but unfortunaly i get a FC
Version installed : 1.0 from fdroid on CM11
Already tried without success : moving app to /system/app

Logcat : 
I/ActivityManager( 1935): Timeline: Activity_launch_request id:edu.harvard.android.mmskeeper time:17170024
I/ActivityManager( 1707): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=edu.harvard.android.mmskeeper/.MMSKeeper} from pid 1935
W/UsageStats( 1707): Failed writing stats to file:/data/system/usagestats/usage-20140129
I/ActivityManager( 1707): Start proc edu.harvard.android.mmskeeper for activity edu.harvard.android.mmskeeper/.MMSKeeper: pid=13923 uid=10153 gids={50153}
D/ActivityThread(13923): edu.harvard.android.mmskeeper black listed for hwui
D/AndroidRuntime(13923): Shutting down VM
W/dalvikvm(13923): threadid=1: thread exiting with uncaught exception (group=0x4153dc80)
E/AndroidRuntime(13923): FATAL EXCEPTION: main
E/AndroidRuntime(13923): Process: edu.harvard.android.mmskeeper, PID: 13923
E/AndroidRuntime(13923): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{edu.harvard.android.mmskeeper/edu.harvard.android.mmskeeper.MMSKeeper}: java.lang.ClassCastException: edu.harvard.android.mmskeeper.MMSKeeper cannot be cast to android.app.Activity
E/AndroidRuntime(13923):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2131)
E/AndroidRuntime(13923):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2265)
E/AndroidRuntime(13923):        at android.app.ActivityThread.access$800(ActivityThread.java:145)
E/AndroidRuntime(13923):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
E/AndroidRuntime(13923):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(13923):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(13923):        at android.app.ActivityThread.main(ActivityThread.java:5114)
E/AndroidRuntime(13923):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(13923):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(13923):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/AndroidRuntime(13923):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime(13923):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(13923): Caused by: java.lang.ClassCastException: edu.harvard.android.mmskeeper.MMSKeeper cannot be cast to android.app.Activity
E/AndroidRuntime(13923):        at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
E/AndroidRuntime(13923):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2122)
E/AndroidRuntime(13923):        ... 11 more
E/DropBoxManagerService( 1707): Can't write: system_app_crash
E/DropBoxManagerService( 1707): java.io.FileNotFoundException: /data/system/dropbox/drop605.tmp: open failed: EACCES (Permission denied)
E/DropBoxManagerService( 1707):         at libcore.io.IoBridge.open(IoBridge.java:409)
E/DropBoxManagerService( 1707):         at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
E/DropBoxManagerService( 1707):         at java.io.FileOutputStream.<init>(FileOutputStream.java:73)
E/DropBoxManagerService( 1707):         at com.android.server.DropBoxManagerService.add(DropBoxManagerService.java:211)
E/DropBoxManagerService( 1707):         at android.os.DropBoxManager.addText(DropBoxManager.java:272)
E/DropBoxManagerService( 1707):         at com.android.server.am.ActivityManagerService$18.run(ActivityManagerService.java:10137)
E/DropBoxManagerService( 1707): Caused by: libcore.io.ErrnoException: open failed: EACCES (Permission denied)
E/DropBoxManagerService( 1707):         at libcore.io.Posix.open(Native Method)
E/DropBoxManagerService( 1707):         at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
E/DropBoxManagerService( 1707):         at libcore.io.IoBridge.open(IoBridge.java:393)
E/DropBoxManagerService( 1707):         ... 5 more
W/ActivityManager( 1707):   Force finishing activity edu.harvard.android.mmskeeper/.MMSKeeper
W/UsageStats( 1707): Failed writing stats to file:/data/system/usagestats/usage-20140129
W/ActivityManager( 1707): Activity pause timeout for ActivityRecord{41d0f7e8 u0 edu.harvard.android.mmskeeper/.MMSKeeper t70 f}
I/ActivityManager( 1935): Timeline: Activity_idle id: android.os.BinderProxy@417fe590 time:17171737
I/ActivityManager( 1707): Timeline: Activity_windows_visible id: ActivityRecord{41cbf950 u0 com.android.launcher3/.Launcher t1} time:17172172

**Comment by faxm0dem** [comment]
Same here on nexus 4 cm11

**Comment by bencebeky** [comment]
Hi ewilly and faxm0dem,

Thank you very much for your feedback. Ewilly, I am especially grateful that you took the effort to sign up for github just to be able to open this issue.

Unfortunately there was a severe bug in my code, which I managed to fix. The new version 1.01 is now avaliable on github. I submitted a merge request to f-droid/fdroiddata to update to this version. After this request is accepted by f-droid developers, the new version of MMSKeeper will build and become available through F-Droid within maybe a few hours.

I would be very grateful if you could check the new version and let me know if you still experience any issues. Thank you again for your help.

Bence

**Comment by matwillshak** [comment]
Another problem with the new version : error message when the app is open, it says it need to be a system app, but I have already moved the app to /system/app

**Comment by bencebeky** [comment]
@matwillshak I myself had difficulties converting apps to system apps. Please try installing the [/system/app mover app](https://f-droid.org/repository/browse/?fdid=de.j4velin.systemappmover) from F-Droid, and using that to convert MMSKeeper to a system app. Make sure to reboot your device. If the problem persist, please feel free to open a new issue.

As the original problem this issue was opened for seems to be solved, I'm closing this issue. Thank you all again for your feedback.
